# Dataset Exploration: Wikidata Musicians

Each task folder has a `source.csv`, a `target.csv`, and a `groundtruth.csv` mapping source columns to target columns.

In [1]:
from pathlib import Path

import pandas as pd
from IPython.display import display

DATA_DIR = Path("../datasets/WikidataHumanCurated/Musicians")

In [2]:
tasks = {}
for task_dir in sorted(DATA_DIR.iterdir()):
    if task_dir.is_dir():
        tasks[task_dir.name] = {
            name: pd.read_csv(task_dir / f"{name}.csv")
            for name in ["source", "target", "groundtruth"]
        }

for task, dfs in tasks.items():
    print(task, {name: df.shape for name, df in dfs.items()})

Musicians_joinable {'source': (10845, 13), 'target': (10845, 13), 'groundtruth': (6, 2)}
Musicians_semjoinable {'source': (10845, 14), 'target': (10845, 14), 'groundtruth': (8, 2)}
Musicians_unionable {'source': (10845, 20), 'target': (10845, 20), 'groundtruth': (20, 2)}
Musicians_viewunion {'source': (5422, 13), 'target': (5423, 13), 'groundtruth': (6, 2)}

## Musicians_joinable

In [3]:
for name, df in tasks["Musicians_joinable"].items():
    print(name)
    display(df.head())

source

,musician,birthDate,familyNameLabel,givenNameLabel,numberOfChildren,websiteLabel,residenceLabel,ethnicityLabel,religionLabel,activityStart,twitterNameLabel,geniusNameLabel,recordLabelLabel
0,http://www.wikidata.org/entity/Q6096,1971-10-20T00:00:00Z,Broadus,Cordozar,4.0,http://snoopdogg.com/,NaN,African Americans,Islam,1991-01-01T00:00:00Z,snoopdogg,Snoop-dogg,Death Row Records
1,http://www.wikidata.org/entity/Q5977,1936-09-07T00:00:00Z,Holley,Hardin,NaN,http://www.buddyholly.com,NaN,NaN,Baptists,1952-01-01T00:00:00Z,NaN,Buddy-holly,Brunswick
2,http://www.wikidata.org/entity/Q8349,1959-10-23T00:00:00Z,Yankovic,Alfred,NaN,http://weirdal.com/,NaN,NaN,Christianity,1976-01-01T00:00:00Z,alyankovic,Weird-al-yankovic,Volcano Entertainment
3,http://www.wikidata.org/entity/Q1779,1901-08-04T00:00:00Z,Armstrong,Louis,NaN,http://www.louisarmstronghouse.org/,NaN,African Americans,NaN,1914-01-01T00:00:00Z,NaN,NaN,Decca
4,http://www.wikidata.org/entity/Q4270,1975-12-13T00:00:00Z,Delonge,Thomas,NaN,http://blink-182.com/,Del Mar,NaN,NaN,1992-01-01T00:00:00Z,tomdelonge,Tom-delonge,DGC Records

target

,musicianID,musicianName,genderType,birthDate,city,familyName,forename,fatherName,motherName,spouse,NChildren,kind,webpage
0,http://www.wikidata.org/entity/Q6096,Bigg Snoop Dogg,m,1971-10-20T00:00:00Z,Long Beach,Broadus,Cordozar,NaN,NaN,NaN,4.0,African-American music,http://snoopdogg.com/
1,http://www.wikidata.org/entity/Q5977,00085469927 IPI,m,1936-09-07T00:00:00Z,Lubbock,Holley,Hardin,NaN,NaN,Maria Elena Holly,NaN,rock and roll,http://www.buddyholly.com
2,http://www.wikidata.org/entity/Q8349,Al Yankovic,m,1959-10-23T00:00:00Z,Downey,Yankovic,Alfred,Nick Louis Yankovic,Mary Yankovic,Suzanne Yankovic,NaN,humor,http://weirdal.com/
3,http://www.wikidata.org/entity/Q1779,Pops,m,1901-08-04T00:00:00Z,New Orleans,Armstrong,Louis,NaN,NaN,Lil Hardin Armstrong,NaN,popular music,http://www.louisarmstronghouse.org/
4,http://www.wikidata.org/entity/Q4270,Ava DeLonge,m,1975-12-13T00:00:00Z,Poway,Delonge,Thomas,NaN,NaN,Jennifer DeLonge,NaN,pop music,http://blink-182.com/

groundtruth

             source      target
0          musician  musicianID
1         birthDate   birthDate
2   familyNameLabel  familyName
3    givenNameLabel    forename
4  numberOfChildren   NChildren

## Musicians_semjoinable

In [4]:
for name, df in tasks["Musicians_semjoinable"].items():
    print(name)
    display(df.head())

source

,musician,musicianLabel,genderLabel,cityLabel,fatherLabel,motherLabel,partner,genreLabel,ethnicityLabel,religionLabel,activityStart,twitterNameLabel,geniusNameLabel,recordLabelLabel
0,http://www.wikidata.org/entity/Q6096,Snoop Dogg,male,Long Beach,NaN,NaN,NaN,West Coast hip hop,African Americans,Islam,1991-01-01T00:00:00Z,snoopdogg,Snoop-dogg,Death Row Records
1,http://www.wikidata.org/entity/Q5977,Buddy Holly,male,Lubbock,NaN,NaN,María Elena Holly,beat music,NaN,Baptists,1952-01-01T00:00:00Z,NaN,Buddy-holly,Brunswick
2,http://www.wikidata.org/entity/Q8349,"""Weird Al"" Yankovic",male,Downey,Nick Yankovic,Mary Yankovic,Suzanne Yankovic,nerdcore,NaN,Christianity,1976-01-01T00:00:00Z,alyankovic,Weird-al-yankovic,Volcano Entertainment
3,http://www.wikidata.org/entity/Q1779,Louis Armstrong,male,New Orleans,NaN,NaN,Lil Hardin Armstrong,jazz,African Americans,NaN,1914-01-01T00:00:00Z,NaN,NaN,Decca
4,http://www.wikidata.org/entity/Q4270,Tom DeLonge,male,Poway,NaN,NaN,Jennifer DeLonge,pop punk,NaN,NaN,1992-01-01T00:00:00Z,tomdelonge,Tom-delonge,DGC Records

target

,musicianID,musicianName,genderType,birthDate,city,familyName,forename,fatherName,motherName,spouse,NChildren,kind,webpage,residence
0,http://www.wikidata.org/entity/Q6096,Bigg Snoop Dogg,m,1971-10-20T00:00:00Z,Long Beach,Broadus,Cordozar,NaN,NaN,NaN,4.0,African-American music,http://snoopdogg.com/,NaN
1,http://www.wikidata.org/entity/Q5977,00085469927 IPI,m,1936-09-07T00:00:00Z,Lubbock,Holley,Hardin,NaN,NaN,Maria Elena Holly,NaN,rock and roll,http://www.buddyholly.com,NaN
2,http://www.wikidata.org/entity/Q8349,Al Yankovic,m,1959-10-23T00:00:00Z,Downey,Yankovic,Alfred,Nick Louis Yankovic,Mary Yankovic,Suzanne Yankovic,NaN,humor,http://weirdal.com/,NaN
3,http://www.wikidata.org/entity/Q1779,Pops,m,1901-08-04T00:00:00Z,New Orleans,Armstrong,Louis,NaN,NaN,Lil Hardin Armstrong,NaN,popular music,http://www.louisarmstronghouse.org/,NaN
4,http://www.wikidata.org/entity/Q4270,Ava DeLonge,m,1975-12-13T00:00:00Z,Poway,Delonge,Thomas,NaN,NaN,Jennifer DeLonge,NaN,pop music,http://blink-182.com/,Del Mar

groundtruth

          source        target
0       musician    musicianID
1  musicianLabel  musicianName
2    genderLabel    genderType
3      cityLabel          city
4    fatherLabel    fatherName

## Musicians_unionable

In [5]:
for name, df in tasks["Musicians_unionable"].items():
    print(name)
    display(df.head())

source

,musician,musicianLabel,genderLabel,birthDate,cityLabel,familyNameLabel,givenNameLabel,fatherLabel,motherLabel,partner,numberOfChildren,genreLabel,websiteLabel,residenceLabel,ethnicityLabel,religionLabel,activityStart,twitterNameLabel,geniusNameLabel,recordLabelLabel
0,http://www.wikidata.org/entity/Q6096,Snoop Dogg,male,1971-10-20T00:00:00Z,Long Beach,Broadus,Cordozar,NaN,NaN,NaN,4.0,West Coast hip hop,http://snoopdogg.com/,NaN,African Americans,Islam,1991-01-01T00:00:00Z,snoopdogg,Snoop-dogg,Death Row Records
1,http://www.wikidata.org/entity/Q5977,Buddy Holly,male,1936-09-07T00:00:00Z,Lubbock,Holley,Hardin,NaN,NaN,María Elena Holly,NaN,beat music,http://www.buddyholly.com,NaN,NaN,Baptists,1952-01-01T00:00:00Z,NaN,Buddy-holly,Brunswick
2,http://www.wikidata.org/entity/Q8349,"""Weird Al"" Yankovic",male,1959-10-23T00:00:00Z,Downey,Yankovic,Alfred,Nick Yankovic,Mary Yankovic,Suzanne Yankovic,NaN,nerdcore,http://weirdal.com/,NaN,NaN,Christianity,1976-01-01T00:00:00Z,alyankovic,Weird-al-yankovic,Volcano Entertainment
3,http://www.wikidata.org/entity/Q1779,Louis Armstrong,male,1901-08-04T00:00:00Z,New Orleans,Armstrong,Louis,NaN,NaN,Lil Hardin Armstrong,NaN,jazz,http://www.louisarmstronghouse.org/,NaN,African Americans,NaN,1914-01-01T00:00:00Z,NaN,NaN,Decca
4,http://www.wikidata.org/entity/Q4270,Tom DeLonge,male,1975-12-13T00:00:00Z,Poway,Delonge,Thomas,NaN,NaN,Jennifer DeLonge,NaN,pop punk,http://blink-182.com/,Del Mar,NaN,NaN,1992-01-01T00:00:00Z,tomdelonge,Tom-delonge,DGC Records

target

,musicianID,musicianName,genderType,birthDate,city,familyName,forename,fatherName,motherName,spouse,NChildren,kind,webpage,residence,ethnicity,religionLabel,kickoff,twitterUsername,geniusNameLabel,recordCompany
0,http://www.wikidata.org/entity/Q6096,Bigg Snoop Dogg,m,1971-10-20T00:00:00Z,Long Beach,Broadus,Cordozar,NaN,NaN,NaN,4.0,African-American music,http://snoopdogg.com/,NaN,African Americans,Islam,1991-01-01T00:00:00Z,snoopdogg,Snoop-dogg,Death Row Records
1,http://www.wikidata.org/entity/Q5977,00085469927 IPI,m,1936-09-07T00:00:00Z,Lubbock,Holley,Hardin,NaN,NaN,Maria Elena Holly,NaN,rock and roll,http://www.buddyholly.com,NaN,NaN,Baptists,1952-01-01T00:00:00Z,NaN,Buddy-holly,Brunswick
2,http://www.wikidata.org/entity/Q8349,Al Yankovic,m,1959-10-23T00:00:00Z,Downey,Yankovic,Alfred,Nick Louis Yankovic,Mary Yankovic,Suzanne Yankovic,NaN,humor,http://weirdal.com/,NaN,NaN,Christianity,1976-01-01T00:00:00Z,alyankovic,Weird-al-yankovic,Volcano Entertainment
3,http://www.wikidata.org/entity/Q1779,Pops,m,1901-08-04T00:00:00Z,New Orleans,Armstrong,Louis,NaN,NaN,Lil Hardin Armstrong,NaN,popular music,http://www.louisarmstronghouse.org/,NaN,African Americans,NaN,1914-01-01T00:00:00Z,NaN,NaN,Decca
4,http://www.wikidata.org/entity/Q4270,Ava DeLonge,m,1975-12-13T00:00:00Z,Poway,Delonge,Thomas,NaN,NaN,Jennifer DeLonge,NaN,pop music,http://blink-182.com/,Del Mar,NaN,NaN,1992-01-01T00:00:00Z,tomdelonge,Tom-delonge,DGC Records

groundtruth

          source        target
0       musician    musicianID
1  musicianLabel  musicianName
2    genderLabel    genderType
3      birthDate     birthDate
4      cityLabel          city

## Musicians_viewunion

In [6]:
for name, df in tasks["Musicians_viewunion"].items():
    print(name)
    display(df.head())

source

,musician,birthDate,familyNameLabel,givenNameLabel,numberOfChildren,websiteLabel,residenceLabel,ethnicityLabel,religionLabel,activityStart,twitterNameLabel,geniusNameLabel,recordLabelLabel
0,http://www.wikidata.org/entity/Q6096,1971-10-20T00:00:00Z,Broadus,Cordozar,4.0,http://snoopdogg.com/,NaN,African Americans,Islam,1991-01-01T00:00:00Z,snoopdogg,Snoop-dogg,Death Row Records
1,http://www.wikidata.org/entity/Q5977,1936-09-07T00:00:00Z,Holley,Hardin,NaN,http://www.buddyholly.com,NaN,NaN,Baptists,1952-01-01T00:00:00Z,NaN,Buddy-holly,Brunswick
2,http://www.wikidata.org/entity/Q8349,1959-10-23T00:00:00Z,Yankovic,Alfred,NaN,http://weirdal.com/,NaN,NaN,Christianity,1976-01-01T00:00:00Z,alyankovic,Weird-al-yankovic,Volcano Entertainment
3,http://www.wikidata.org/entity/Q1779,1901-08-04T00:00:00Z,Armstrong,Louis,NaN,http://www.louisarmstronghouse.org/,NaN,African Americans,NaN,1914-01-01T00:00:00Z,NaN,NaN,Decca
4,http://www.wikidata.org/entity/Q4270,1975-12-13T00:00:00Z,Delonge,Thomas,NaN,http://blink-182.com/,Del Mar,NaN,NaN,1992-01-01T00:00:00Z,tomdelonge,Tom-delonge,DGC Records

target

,musicianID,musicianName,genderType,birthDate,city,familyName,forename,fatherName,motherName,spouse,NChildren,kind,webpage
0,http://www.wikidata.org/entity/Q3017926,NaN,m,1938-08-24T00:00:00Z,Cincinnati,NaN,David,NaN,NaN,NaN,NaN,rock music,NaN
1,http://www.wikidata.org/entity/Q2923750,NaN,m,1962-05-28T00:00:00Z,Bakersfield,Cruz,Brandon,NaN,NaN,NaN,NaN,NaN,NaN
2,http://www.wikidata.org/entity/Q3020857,NaN,f,1965-08-13T00:00:00Z,Sacramento,NaN,Deborah,NaN,NaN,RDJ,NaN,NaN,NaN
3,http://www.wikidata.org/entity/Q3027902,NaN,m,1989-09-17T00:00:00Z,Los Angeles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,http://www.wikidata.org/entity/Q2967586,NaN,m,1936-08-22T00:00:00Z,Gaston,Brown,Chuck,NaN,NaN,NaN,NaN,go-go,http://www.windmeupchuck.com/

groundtruth

             source      target
0          musician  musicianID
1         birthDate   birthDate
2   familyNameLabel  familyName
3    givenNameLabel    forename
4  numberOfChildren   NChildren